services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Placeh0lder!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql_data: